source 'https://rubygems.org'

gem 'rails', '3.2.17'

gem 'sampler', path: '..'

group :assets do
  gem 'slim-rails'
  gem 'ngannotate-rails' #, path: '../ngannotate-rails'
  gem 'bootstrap-sass', '~> 2.3.1.0'
  gem 'sass-rails',   '~> 3.2.3'
  gem 'therubyracer', platforms: :ruby
end

gem 'awesome_print'
gem 'hashie'
gem 'logging-rails'
gem 'nokogiri', '1.5.6'
gem 'protractor-rails'
gem 'capybara'
gem 'rspec'
gem 'rspec-rails'
gem 'capybara-webkit'
gem 'selenium-webdriver'

#gem 'capybara-ng', '0.0.4'
#gem 'capybara-ng', path: '../../capybara-ng'
gem 'capybara-ng', git: 'git@github.com:kikonen/capybara-ng.git', tag: 'v0.0.4'
