source 'https://rubygems.org'

gem 'rails', '3.2.17'

gem 'sampler', path: '..'

group :assets do
  gem 'slim-rails'
  gem 'ngannotate-rails' #, path: '../ngannotate-rails'
  gem 'bootstrap-sass', '~> 2.3.1.0'
  gem 'sass-rails',   '~> 3.2.3'
  gem 'therubyracer', platforms: :ruby
end

gem 'protractor-rails'
